name: CI
on:
  # SECURITY: This must be a push event only, otherwise our M1 mac runner would be compromised by
  # third-party pull requests which could run arbitrary code. This way, we can restrict it to
  # collaborators of the repository only.
  #
  # Whenever GitHub Actions gets official M1 support, we can use that for PRs and get rid of this
  # self-hosted runner: https://github.com/actions/virtual-environments/issues/2187
  push:     
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
jobs:
  aarch64-macos:
    if: ${{ github.repository == 'hexops/mach' }}
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        shell: '/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: zig build
      - name: build (WASM)
        run: zig build -Dtarget=wasm32-freestanding-none
